### ISSUE TITLE
The name field is resized, but remains blank, after USB insertion

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/mintstick#92] opened 2021-11-03 06:45 UTC
To reproduce:

1. `mintstick -m format` without a USB stick inserted.
2. Insert a USB stick, 
3. See that name field - the field after 'format' - has been resized to the size of the name that mintstick gives the USB stick, but that the field is not populated.

What should happen:

At stage 3, either there should be no resizing or, better, the name of the USB stick should appear in the name field.

**Comment by clefebvre** [comment] 2024-01-17 14:19
I can't see a bug here, but I think this was reported prior to some of the UI changes. I'll close this for now since it works as intended.

**Closed by clefebvre** 2024-01-17 14:19 UTC
