### ISSUE TITLE
USB Format Utility issues

### ISSUE THREAD

**Issue by ghost** [linuxmint/mintstick#36] opened 2015-01-16 07:36 UTC
Basically seems that after formating, usb pen permissions get messed up, only opening as root we are able to move/copy things to it.

**Comment by zzitoz** [comment] 2015-01-16 08:33
permissions before format:

http://pastebin.com/P0wZABys

**Comment by zzitoz** [comment] 2015-01-16 08:36
permissions after format:

http://pastebin.com/068vT4NK

both FS were NTFS during the tests.

**Comment by silviucc** [comment] 2015-11-24 15:05
Hi,
 
Permissions are fine but something does go bork. Not quite sure what. The quick workaround is to shut down the file manager and start it again. For Nautilus(Files) the command is ```nautilus -q```. It starts automatically when you attempt to browse a directory.

**Comment by xenopeek** [comment] 2018-02-22 11:25
Thanks for contributing to mintstick. Considering there have been no updates to this issue late 2015 and I'm not able to reproduce it (Linux Mint 18.3 Cinnamon, mintstick 1.3.5, tried with formatting as FAT32 and EXT4) I assume it's no longer affecting users and I'm closing it.

If the issue happens again, please test against the latest mintstick version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintstick.

**Closed by xenopeek** 2018-02-22 11:25 UTC
